### PR TITLE
Various Improvements

### PR DESCRIPTION
**Pull request by kyleconroy**
- Add `find_by_id` methods to projects, users, and tasks.
- Add task search
- Add transaction loading for tasks
- Add many new attributes on tasks

### CODE REVIEW

**Comment by amfeng** [comment]
Did you still want to merge this @kyleconroy?

**Comment by kyleconroy** [comment]
Wow, I had totally forgotten about this PR, let me look it over and see if it's still useful

**Comment by kyleconroy** [comment]
Yep, this still looks good.

**Comment by jshirley** [comment]
:+1: on merging this, will make our lives easier! :)

**Pull request closed without merging**
